version: '3.8'

services:
  qdrant-mcp-server:
    stdin_open: true
    build: .
    environment:
      - FASTMCP_TRANSPORT
    ports:
      - "8080:8080"
      - "8000:8000"

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./${QDRANT_STORAGE_DIR}:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
